trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  AZURE_WEBAPP_NAME: "azurePractice"  # ✅ Replace with your App Service name
  DOCKER_IMAGE_NAME: "$(AZURE_WEBAPP_NAME):$(Build.BuildId)"  # Used to name docker image

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: 'Use Python 3.9'

- script: |
    echo "Building Docker image..."
    docker build -t $(DOCKER_IMAGE_NAME) .
    echo "Docker image built: $(DOCKER_IMAGE_NAME)"
  displayName: 'Build Docker Image'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'azure-rm-conn'  # ✅ Name of your AzureRM service connection
    appName: '$(AZURE_WEBAPP_NAME)'     # ✅ App Service name
    containers: '$(DOCKER_IMAGE_NAME)'  # ✅ Docker image name
  displayName: 'Deploy to Azure Web App'
